//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiControls.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuiControls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap button_hover_Dark {
            get {
                object obj = ResourceManager.GetObject("button_hover_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap button_hover_Flat {
            get {
                object obj = ResourceManager.GetObject("button_hover_Flat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap button_hover_Lite {
            get {
                object obj = ResourceManager.GetObject("button_hover_Lite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SpriteSheet name=&quot;LedButton&quot; image=&quot;LedButton_LEDs&quot; count=&quot;1&quot;&gt;
        ///    &lt;element enum=&quot;Stepflow.Gui.Orientation&quot; count=&quot;3&quot;&gt;
        ///        &lt;group enum=&quot;Stepflow.Gui.Style&quot; count=&quot;3&quot;&gt;
        ///            &lt;sprite name=&quot;Flat&quot; image=&quot;LedButton_Flat&quot;&gt;
        ///                &lt;X&gt;0&lt;/X&gt;
        ///                &lt;Y&gt;0&lt;/Y&gt;
        ///                &lt;W&gt;64&lt;/W&gt;
        ///                &lt;H&gt;64&lt;/H&gt;
        ///            &lt;/sprite&gt;
        ///            &lt;sprite name=&quot;Lite&quot; image=&quot;LedButton_Lite&quot;&gt;
        ///                &lt;X&gt;0&lt;/X&gt;
        ///                &lt;Y&gt;0&lt;/Y&gt;
        ///  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string button_leds_xml {
            get {
                return ResourceManager.GetString("button_leds_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hellebarden {
            get {
                object obj = ResourceManager.GetObject("hellebarden", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap kein_bild {
            get {
                object obj = ResourceManager.GetObject("kein_bild", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LedButton_Dark {
            get {
                object obj = ResourceManager.GetObject("LedButton_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LedButton_Flat {
            get {
                object obj = ResourceManager.GetObject("LedButton_Flat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LedButton_LEDs {
            get {
                object obj = ResourceManager.GetObject("LedButton_LEDs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LedButton_Lite {
            get {
                object obj = ResourceManager.GetObject("LedButton_Lite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap meter_H {
            get {
                object obj = ResourceManager.GetObject("meter_H", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap meter_R {
            get {
                object obj = ResourceManager.GetObject("meter_R", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap meter_V {
            get {
                object obj = ResourceManager.GetObject("meter_V", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SpriteSheet name=&quot;MidiSlider&quot; enum=&quot;Stepflow.Gui.Orientation&quot; count=&quot;3&quot;&gt;
        ///    &lt;element name=&quot;Rondeal&quot; image=&quot;slider_R_png&quot; enum=&quot;Stepflow.Gui.Style&quot; count=&quot;4&quot;&gt;
        ///        &lt;group name=&quot;Flat&quot; count=&quot;2&quot;&gt;
        ///            &lt;group name=&quot;Nipple&quot; enum=&quot;Stepflow.Gui.MipMap&quot; count=&quot;3&quot;&gt;
        ///                &lt;sprite name=&quot;Small&quot;&gt;
        ///                    &lt;X&gt;0&lt;/X&gt;
        ///                    &lt;Y&gt;0&lt;/Y&gt;
        ///                    &lt;W&gt;128&lt;/W&gt;
        ///                    &lt;H&gt;128&lt;/H&gt;
        ///                &lt;/sprite&gt;
        ///         [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string slider_complete_xml {
            get {
                return ResourceManager.GetString("slider_complete_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap slider_H_png {
            get {
                object obj = ResourceManager.GetObject("slider_H_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SpriteSheet name=&quot;Slider&quot; image=&quot;slider_H_png&quot;
        ///             count=&quot;1&quot;&gt;
        ///    &lt;element name=&quot;Horizontal&quot; count=&quot;3&quot;&gt;
        ///        &lt;group name=&quot;Blet&quot; count=&quot;3&quot;&gt;
        ///            &lt;sprite name=&quot;Flat&quot;&gt;
        ///                &lt;X&gt;0&lt;/X&gt;
        ///                &lt;Y&gt;0&lt;/Y&gt;
        ///                &lt;W&gt;256&lt;/W&gt;
        ///                &lt;H&gt;31&lt;/H&gt;
        ///            &lt;/sprite&gt;
        ///            &lt;sprite name=&quot;Lite&quot;&gt;
        ///                &lt;X&gt;0&lt;/X&gt;
        ///                &lt;Y&gt;32&lt;/Y&gt;
        ///                &lt;W&gt;256&lt;/W&gt;
        ///                &lt;H&gt;31&lt;/H&gt;
        ///          [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string slider_Horizontal_xml {
            get {
                return ResourceManager.GetString("slider_Horizontal_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap slider_leds_png {
            get {
                object obj = ResourceManager.GetObject("slider_leds_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SpriteSheet image=&quot;slider_leds_png&quot;
        ///             elements=&quot;1&quot;&gt;
        ///  &lt;element name=&quot;LED&quot; enum=&quot;Stepflow.Gui.Orientation&quot; count=&quot;2&quot;&gt;
        ///      &lt;array name=&quot;Horizontal&quot;
        ///             enum=&quot;Stepflow.Gui.LED&quot; count=&quot;8&quot;
        ///             box=&quot;32&quot; dir=&quot;X&quot;&gt;
        ///          &lt;X&gt;12&lt;/X&gt;
        ///          &lt;Y&gt;2&lt;/Y&gt;
        ///          &lt;W&gt;8&lt;/W&gt;
        ///          &lt;H&gt;28&lt;/H&gt;
        ///      &lt;/array&gt;
        ///      &lt;group name=&quot;Vertical&quot;
        ///             enum=&quot;Stepflow.Gui.LED&quot; count=&quot;8&quot;&gt;
        ///          &lt;sprite name=&quot;Green&quot;&gt;
        ///              &lt;X&gt; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string slider_leds_xml {
            get {
                return ResourceManager.GetString("slider_leds_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap slider_R_png {
            get {
                object obj = ResourceManager.GetObject("slider_R_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SpriteSheet name=&quot;Slider&quot; image=&quot;slider_R_png&quot; enum=&quot;Stepflow.Gui.Orientation&quot; count=&quot;1&quot;&gt;
        ///  &lt;element name=&quot;Rondeal&quot; count=&quot;3&quot;&gt;
        ///      &lt;group name=&quot;Blet&quot; enum=&quot;Stepflow.Gui.Style&quot; count=&quot;3&quot;&gt;
        ///          &lt;sprite name=&quot;Lite&quot;&gt;
        ///              &lt;X&gt;0&lt;/X&gt;
        ///              &lt;Y&gt;128&lt;/Y&gt;
        ///              &lt;W&gt;128&lt;/W&gt;
        ///              &lt;H&gt;128&lt;/H&gt;
        ///          &lt;/sprite&gt;
        ///          &lt;sprite name=&quot;Dark&quot;&gt;
        ///              &lt;X&gt;128&lt;/X&gt;
        ///              &lt;Y&gt;0&lt;/Y&gt;
        ///              &lt;W&gt;128&lt;/W&gt;
        ///              &lt; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string slider_Rondeal_xml {
            get {
                return ResourceManager.GetString("slider_Rondeal_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap slider_V_png {
            get {
                object obj = ResourceManager.GetObject("slider_V_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SpriteSheet name=&quot;Slider&quot; image=&quot;slider_V_png&quot;
        ///             enum=&quot;Stepflow.Gui.Orientation&quot; count=&quot;1&quot;&gt;
        ///    &lt;element name=&quot;Vertical&quot; count=&quot;2&quot;&gt;
        ///        &lt;group name=&quot;Blet&quot; enum=&quot;Stepflow.Gui.Style&quot; count=&quot;3&quot;&gt;
        ///            &lt;sprite name=&quot;Flat&quot;&gt;
        ///                &lt;X&gt;0&lt;/X&gt;
        ///                &lt;Y&gt;0&lt;/Y&gt;
        ///                &lt;W&gt;31&lt;/W&gt;
        ///                &lt;H&gt;256&lt;/H&gt;
        ///            &lt;/sprite&gt;
        ///            &lt;sprite name=&quot;Lite&quot;&gt;
        ///                &lt;X&gt;32&lt;/X&gt;
        ///                &lt;Y&gt;0&lt;/Y&gt;
        ///         [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string slider_Vertical_xml {
            get {
                return ResourceManager.GetString("slider_Vertical_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap umittelung {
            get {
                object obj = ResourceManager.GetObject("umittelung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap umrandunkel {
            get {
                object obj = ResourceManager.GetObject("umrandunkel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
