//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiControls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuiControls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap button_hover_Dark {
            get {
                object obj = ResourceManager.GetObject("button_hover_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap button_hover_Flat {
            get {
                object obj = ResourceManager.GetObject("button_hover_Flat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap button_hover_Lite {
            get {
                object obj = ResourceManager.GetObject("button_hover_Lite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SpriteSheet name=&quot;LedButton&quot; image=&quot;LedButton_LEDs&quot; count=&quot;1&quot;&gt;
        ///    &lt;element enum=&quot;Stepflow.Gui.Orientation&quot; count=&quot;3&quot;&gt;
        ///        &lt;group enum=&quot;Stepflow.Gui.Style&quot; count=&quot;3&quot;&gt;
        ///            &lt;sprite name=&quot;Flat&quot; image=&quot;LedButton_Flat&quot;&gt;
        ///                &lt;X&gt;0&lt;/X&gt;
        ///                &lt;Y&gt;0&lt;/Y&gt;
        ///                &lt;W&gt;64&lt;/W&gt;
        ///                &lt;H&gt;64&lt;/H&gt;
        ///            &lt;/sprite&gt;
        ///            &lt;sprite name=&quot;Lite&quot; image=&quot;LedButton_Lite&quot;&gt;
        ///                &lt;X&gt;0&lt;/X&gt;
        ///                &lt;Y&gt;0&lt;/Y&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string button_leds_xml {
            get {
                return ResourceManager.GetString("button_leds_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hellebarden {
            get {
                object obj = ResourceManager.GetObject("hellebarden", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap kein_bild {
            get {
                object obj = ResourceManager.GetObject("kein_bild", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SpriteSheet image=&quot;LedButton_Small&quot; count=&quot;3&quot;&gt;
        ///	&lt;element name=&quot;LedButton&quot; enum=&quot;Stepflow.Gui.MipMap&quot; count=&quot;3&quot;&gt;
        ///		&lt;group name=&quot;Large&quot; enum=&quot;Stepflow.Gui.Style&quot; count=&quot;3&quot;&gt;
        ///			&lt;group name=&quot;Flat&quot; count=&quot;2&quot;&gt;
        ///				&lt;sprite name=&quot;BackG&quot; image=&quot;LedButton_Flat&quot;&gt;
        ///					&lt;X&gt;0&lt;/X&gt;
        ///					&lt;Y&gt;0&lt;/Y&gt;
        ///					&lt;W&gt;64&lt;/W&gt;
        ///					&lt;H&gt;64&lt;/H&gt;
        ///				&lt;/sprite&gt;
        ///				&lt;sprite name=&quot;Hover&quot; image=&quot;button_flat_hover&quot;&gt;
        ///					&lt;X&gt;0&lt;/X&gt;
        ///					&lt;Y&gt;0&lt;/Y&gt;
        ///					&lt;W&gt;64&lt;/W&gt;
        ///					&lt;H&gt;64&lt;/H&gt;
        ///				&lt;/sprite&gt;
        ///			&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ledbutton_complete_xml {
            get {
                return ResourceManager.GetString("ledbutton_complete_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LedButton_Dark {
            get {
                object obj = ResourceManager.GetObject("LedButton_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LedButton_Flat {
            get {
                object obj = ResourceManager.GetObject("LedButton_Flat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LedButton_LEDs {
            get {
                object obj = ResourceManager.GetObject("LedButton_LEDs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LedButton_Lite {
            get {
                object obj = ResourceManager.GetObject("LedButton_Lite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LedButton_Small {
            get {
                object obj = ResourceManager.GetObject("LedButton_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap meter_H {
            get {
                object obj = ResourceManager.GetObject("meter_H", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap meter_R {
            get {
                object obj = ResourceManager.GetObject("meter_R", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap meter_V {
            get {
                object obj = ResourceManager.GetObject("meter_V", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SpriteSheet name=&quot;MidiSlider&quot; enum=&quot;Stepflow.Gui.Orientation&quot; count=&quot;3&quot;&gt;
        ///    &lt;element name=&quot;Rondeal&quot; image=&quot;slider_R_png&quot; enum=&quot;Stepflow.Gui.Style&quot; count=&quot;4&quot;&gt;
        ///        &lt;group name=&quot;Flat&quot; count=&quot;2&quot;&gt;
        ///            &lt;group name=&quot;Nipple&quot; enum=&quot;Stepflow.Gui.MipMap&quot; count=&quot;3&quot;&gt;
        ///                &lt;sprite name=&quot;Small&quot;&gt;
        ///                    &lt;X&gt;0&lt;/X&gt;
        ///                    &lt;Y&gt;0&lt;/Y&gt;
        ///                    &lt;W&gt;128&lt;/W&gt;
        ///                    &lt;H&gt;128&lt;/H&gt;
        ///                &lt;/sprite&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string slider_complete_xml {
            get {
                return ResourceManager.GetString("slider_complete_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap slider_H_png {
            get {
                object obj = ResourceManager.GetObject("slider_H_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SpriteSheet name=&quot;Slider&quot; image=&quot;slider_H_png&quot;
        ///             count=&quot;1&quot;&gt;
        ///    &lt;element name=&quot;Horizontal&quot; count=&quot;3&quot;&gt;
        ///        &lt;group name=&quot;Blet&quot; count=&quot;3&quot;&gt;
        ///            &lt;sprite name=&quot;Flat&quot;&gt;
        ///                &lt;X&gt;0&lt;/X&gt;
        ///                &lt;Y&gt;0&lt;/Y&gt;
        ///                &lt;W&gt;256&lt;/W&gt;
        ///                &lt;H&gt;31&lt;/H&gt;
        ///            &lt;/sprite&gt;
        ///            &lt;sprite name=&quot;Lite&quot;&gt;
        ///                &lt;X&gt;0&lt;/X&gt;
        ///                &lt;Y&gt;32&lt;/Y&gt;
        ///                &lt;W&gt;256&lt;/W&gt;
        ///                &lt;H&gt;31&lt;/H&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        public static string slider_Horizontal_xml {
            get {
                return ResourceManager.GetString("slider_Horizontal_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap slider_leds_png {
            get {
                object obj = ResourceManager.GetObject("slider_leds_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SpriteSheet image=&quot;slider_leds_png&quot;
        ///             elements=&quot;1&quot;&gt;
        ///  &lt;element name=&quot;LED&quot; enum=&quot;Stepflow.Gui.Orientation&quot; count=&quot;2&quot;&gt;
        ///      &lt;array name=&quot;Horizontal&quot;
        ///             enum=&quot;Stepflow.Gui.LED&quot; count=&quot;8&quot;
        ///             box=&quot;32&quot; dir=&quot;X&quot;&gt;
        ///          &lt;X&gt;12&lt;/X&gt;
        ///          &lt;Y&gt;2&lt;/Y&gt;
        ///          &lt;W&gt;8&lt;/W&gt;
        ///          &lt;H&gt;28&lt;/H&gt;
        ///      &lt;/array&gt;
        ///      &lt;group name=&quot;Vertical&quot;
        ///             enum=&quot;Stepflow.Gui.LED&quot; count=&quot;8&quot;&gt;
        ///          &lt;sprite name=&quot;Green&quot;&gt;
        ///              &lt;X&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string slider_leds_xml {
            get {
                return ResourceManager.GetString("slider_leds_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap slider_R_png {
            get {
                object obj = ResourceManager.GetObject("slider_R_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SpriteSheet name=&quot;Slider&quot; image=&quot;slider_R_png&quot; enum=&quot;Stepflow.Gui.Orientation&quot; count=&quot;1&quot;&gt;
        ///  &lt;element name=&quot;Rondeal&quot; count=&quot;3&quot;&gt;
        ///      &lt;group name=&quot;Blet&quot; enum=&quot;Stepflow.Gui.Style&quot; count=&quot;3&quot;&gt;
        ///          &lt;sprite name=&quot;Lite&quot;&gt;
        ///              &lt;X&gt;0&lt;/X&gt;
        ///              &lt;Y&gt;128&lt;/Y&gt;
        ///              &lt;W&gt;128&lt;/W&gt;
        ///              &lt;H&gt;128&lt;/H&gt;
        ///          &lt;/sprite&gt;
        ///          &lt;sprite name=&quot;Dark&quot;&gt;
        ///              &lt;X&gt;128&lt;/X&gt;
        ///              &lt;Y&gt;0&lt;/Y&gt;
        ///              &lt;W&gt;128&lt;/W&gt;
        ///              &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string slider_Rondeal_xml {
            get {
                return ResourceManager.GetString("slider_Rondeal_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap slider_V_png {
            get {
                object obj = ResourceManager.GetObject("slider_V_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SpriteSheet name=&quot;Slider&quot; image=&quot;slider_V_png&quot;
        ///             enum=&quot;Stepflow.Gui.Orientation&quot; count=&quot;1&quot;&gt;
        ///    &lt;element name=&quot;Vertical&quot; count=&quot;2&quot;&gt;
        ///        &lt;group name=&quot;Blet&quot; enum=&quot;Stepflow.Gui.Style&quot; count=&quot;3&quot;&gt;
        ///            &lt;sprite name=&quot;Flat&quot;&gt;
        ///                &lt;X&gt;0&lt;/X&gt;
        ///                &lt;Y&gt;0&lt;/Y&gt;
        ///                &lt;W&gt;31&lt;/W&gt;
        ///                &lt;H&gt;256&lt;/H&gt;
        ///            &lt;/sprite&gt;
        ///            &lt;sprite name=&quot;Lite&quot;&gt;
        ///                &lt;X&gt;32&lt;/X&gt;
        ///                &lt;Y&gt;0&lt;/Y&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string slider_Vertical_xml {
            get {
                return ResourceManager.GetString("slider_Vertical_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap umittelung {
            get {
                object obj = ResourceManager.GetObject("umittelung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap umrandunkel {
            get {
                object obj = ResourceManager.GetObject("umrandunkel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
